apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}
spec:
  selector:
    app: {{ .Values.front.name }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}-canary
spec:
  selector:
    app: {{ .Values.front.name }}-canary
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
