apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blueGreen.activeService }}
spec:
  selector:
    app: {{ .Values.front.name }}
    version: blue
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blueGreen.previewService }}
spec:
  selector:
    app: {{ .Values.front.name }}
    version: green
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
