apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: front-app-rollout
spec:
  replicas: {{ .Values.front.replicaCount }}
  strategy:
    blueGreen:
      activeService: {{ .Values.blueGreen.activeService }}
      previewService: {{ .Values.blueGreen.previewService }}
      autoPromotionEnabled: {{ .Values.blueGreen.strategy.autoPromotionEnabled }}
  selector:
    matchLabels:
      app: {{ .Values.front.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.front.name }}
    spec:
      containers:
        - name: front
          image: {{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}
          ports:
            - containerPort: 3000
