apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.front.name }}
  labels:
    app: {{ .Values.front.name }}
spec:
  replicas: {{ .Values.front.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.front.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.front.name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: front
          image: {{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    app: {{ .Values.gateway.name }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.gateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gateway.name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: gateway
          image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
          ports:
            - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend-service
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 4001
